{% set name = "gama" %}
{% set version = "2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/gama/gama-{{ version }}.tar.gz
  sha256: 5cd8bb4a6784e3393cd640075ad2162fb6758e74ea7807bbd72d96b8cbe05d0d
  patches:
    - 0001-observation-cctype.patch
    - 0002-krum-input-cctype.patch
    - 0003-krum-output-cctype.patch
    - 0004-krumm-string-matrix-algorithm.patch

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.5  # [win]
    - make  # [not win]

test:
  commands:
    - gama-local --version
    # gama-g3 --version # should also be test but returns 1 and thus fails the test

about:
  home: https://www.gnu.org/software/gama/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: Adjustment of geodetic networks
  description: |
    GNU Gama is a project dedicated to adjustment of geodetic networks.
    It is intended for use with traditional geodetic surveyings which are
    still used and needed in special measurements (e.g., underground or
    high precision engineering measurements) where the Global Positioning
    System (GPS) cannot be used.
  doc_url: https://www.gnu.org/software/gama/manual/gama.html
  dev_url: https://git.savannah.gnu.org/cgit/gama.git

extra:
  recipe-maintainers:
    - kbevers
