{% set name = "gama" %}
{% set version = "2.06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/gama/gama-{{ version }}.tar.gz
  sha256: 9710a8e973866d941da9a2e8ab730392cc7ee4fb8bbdaa9da866a504e41cb71b
  patches:
    - 0001-observation-cctype.patch

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c')}}
    - {{ compiler('cxx') }}
    - cmake >=3.5  # [win]

test:
  commands:
    - gama-local --version
    # gama-g3 --version # should also be test but returns 1 and thus fails the test

about:
  home: https://www.gnu.org/software/gama/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'Adjustment of geodetic networks'
  description: |
    GNU Gama is a project dedicated to adjustment of geodetic networks.
    It is intended for use with traditional geodetic surveyings which are
    still used and needed in special measurements (e.g., underground or
    high precision engineering measurements) where the Global Positioning
    System (GPS) cannot be used.
  doc_url: https://www.gnu.org/software/gama/manual/gama.html
  dev_url: https://git.savannah.gnu.org/cgit/gama.git

extra:
  recipe-maintainers:
    - kbevers
