appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kf3CVdj5Jjd0atu11pBW0TpneRF9swflarnevRZdSWkfk2slF0uoCbf0l29DWao/pB9zv+HvO8Thu8TW4iiRn9GQ9ZfVeNzw5egLyLB3kRbtTPwzj/8ePtdUzFPet+1emJT0CQ2NjHJg0t1SdyR7hx/3Jj+EqGeDbuEQ1eFrSghNn2+JLbSwZKaBtqo23CkxddFTjnHvpTzzx8UMmQqxvSCEdA4HhvbILWMgYdbp30wxbWdK2bvnjiZDXTBrva/xrae77R9JCrr6Td2qb6NeKVDJxcJSR5FRdfAnfF+6N05wxXlEmQWpnGGQqxVJNb1AYyjDMdfWSmE3wYF7rhg+rbrc5SlX4F3KtCZ8bFoQWNmD28pp8t9azZ7y/gjZZVzFqfzNO6vb4nnGzA12Xc6k1qwCNhbekZ3IQrFYwnlYAx0/lUqoWLkwr8gMHaOJIIRzpSWmUiBqKwpX2pC0wdV9YJ204SRGYwkglhMkF6lfMI6xmX8tUyPfNrxvpqWGhLK0PsjQVq342uXlYU/XeadNnQrDlTgn5BKuUd3JjtK6z1E6acocBp90JeKF+a7ZimB8FvYR6pr5ZByv7znK8VWXVv0kfMqqFo6ADvVLzj5B6B97c/99JrnOSR2QoiHeXtZWw9Fmh+hER88JsGrcO3o6YZuns2n8GAtlqmldJAiLjGQ=}
provider:
  win: azure
conda_forge_output_validation: true
